package org.apache.fontbox.cff;

import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.media3.extractor.ts.PsExtractor;
import com.github.jaiimageio.plugins.tiff.BaselineTIFFTagSet;
import com.github.jaiimageio.plugins.tiff.FaxTIFFTagSet;
import org.bouncycastle.crypto.tls.CipherSuite;
import org.jmrtd.cbeff.ISO781611;

/* loaded from: classes5.dex */
public final class CFFExpertCharset extends CFFCharset {
    private static final CFFExpertCharset INSTANCE;

    private CFFExpertCharset() {
        super(false);
    }

    public static CFFExpertCharset getInstance() {
        return INSTANCE;
    }

    static {
        CFFExpertCharset cFFExpertCharset = new CFFExpertCharset();
        INSTANCE = cFFExpertCharset;
        cFFExpertCharset.addSID(0, 0, ".notdef");
        cFFExpertCharset.addSID(1, 1, "space");
        cFFExpertCharset.addSID(2, 229, "exclamsmall");
        cFFExpertCharset.addSID(3, 230, "Hungarumlautsmall");
        cFFExpertCharset.addSID(4, 231, "dollaroldstyle");
        cFFExpertCharset.addSID(5, 232, "dollarsuperior");
        cFFExpertCharset.addSID(6, 233, "ampersandsmall");
        cFFExpertCharset.addSID(7, 234, "Acutesmall");
        cFFExpertCharset.addSID(8, 235, "parenleftsuperior");
        cFFExpertCharset.addSID(9, 236, "parenrightsuperior");
        cFFExpertCharset.addSID(10, 237, "twodotenleader");
        cFFExpertCharset.addSID(11, 238, "onedotenleader");
        cFFExpertCharset.addSID(12, 13, "comma");
        cFFExpertCharset.addSID(13, 14, "hyphen");
        cFFExpertCharset.addSID(14, 15, TypedValues.CycleType.S_WAVE_PERIOD);
        cFFExpertCharset.addSID(15, 99, "fraction");
        cFFExpertCharset.addSID(16, 239, "zerooldstyle");
        cFFExpertCharset.addSID(17, PsExtractor.VIDEO_STREAM_MASK, "oneoldstyle");
        cFFExpertCharset.addSID(18, 241, "twooldstyle");
        cFFExpertCharset.addSID(19, 242, "threeoldstyle");
        cFFExpertCharset.addSID(20, 243, "fouroldstyle");
        cFFExpertCharset.addSID(21, 244, "fiveoldstyle");
        cFFExpertCharset.addSID(22, 245, "sixoldstyle");
        cFFExpertCharset.addSID(23, 246, "sevenoldstyle");
        cFFExpertCharset.addSID(24, 247, "eightoldstyle");
        cFFExpertCharset.addSID(25, 248, "nineoldstyle");
        cFFExpertCharset.addSID(26, 27, "colon");
        cFFExpertCharset.addSID(27, 28, "semicolon");
        cFFExpertCharset.addSID(28, 249, "commasuperior");
        cFFExpertCharset.addSID(29, 250, "threequartersemdash");
        cFFExpertCharset.addSID(30, 251, "periodsuperior");
        cFFExpertCharset.addSID(31, 252, "questionsmall");
        cFFExpertCharset.addSID(32, 253, "asuperior");
        cFFExpertCharset.addSID(33, 254, "bsuperior");
        cFFExpertCharset.addSID(34, 255, "centsuperior");
        cFFExpertCharset.addSID(35, 256, "dsuperior");
        cFFExpertCharset.addSID(36, 257, "esuperior");
        cFFExpertCharset.addSID(37, 258, "isuperior");
        cFFExpertCharset.addSID(38, BaselineTIFFTagSet.TAG_COMPRESSION, "lsuperior");
        cFFExpertCharset.addSID(39, 260, "msuperior");
        cFFExpertCharset.addSID(40, 261, "nsuperior");
        cFFExpertCharset.addSID(41, BaselineTIFFTagSet.TAG_PHOTOMETRIC_INTERPRETATION, "osuperior");
        cFFExpertCharset.addSID(42, BaselineTIFFTagSet.TAG_THRESHHOLDING, "rsuperior");
        cFFExpertCharset.addSID(43, BaselineTIFFTagSet.TAG_CELL_WIDTH, "ssuperior");
        cFFExpertCharset.addSID(44, BaselineTIFFTagSet.TAG_CELL_LENGTH, "tsuperior");
        cFFExpertCharset.addSID(45, BaselineTIFFTagSet.TAG_FILL_ORDER, "ff");
        cFFExpertCharset.addSID(46, 109, "fi");
        cFFExpertCharset.addSID(47, 110, "fl");
        cFFExpertCharset.addSID(48, 267, "ffi");
        cFFExpertCharset.addSID(49, 268, "ffl");
        cFFExpertCharset.addSID(50, BaselineTIFFTagSet.TAG_DOCUMENT_NAME, "parenleftinferior");
        cFFExpertCharset.addSID(51, 270, "parenrightinferior");
        cFFExpertCharset.addSID(52, BaselineTIFFTagSet.TAG_MAKE, "Circumflexsmall");
        cFFExpertCharset.addSID(53, BaselineTIFFTagSet.TAG_MODEL, "hyphensuperior");
        cFFExpertCharset.addSID(54, BaselineTIFFTagSet.TAG_STRIP_OFFSETS, "Gravesmall");
        cFFExpertCharset.addSID(55, BaselineTIFFTagSet.TAG_ORIENTATION, "Asmall");
        cFFExpertCharset.addSID(56, 275, "Bsmall");
        cFFExpertCharset.addSID(57, 276, "Csmall");
        cFFExpertCharset.addSID(58, BaselineTIFFTagSet.TAG_SAMPLES_PER_PIXEL, "Dsmall");
        cFFExpertCharset.addSID(59, BaselineTIFFTagSet.TAG_ROWS_PER_STRIP, "Esmall");
        cFFExpertCharset.addSID(60, BaselineTIFFTagSet.TAG_STRIP_BYTE_COUNTS, "Fsmall");
        cFFExpertCharset.addSID(61, BaselineTIFFTagSet.TAG_MIN_SAMPLE_VALUE, "Gsmall");
        cFFExpertCharset.addSID(62, BaselineTIFFTagSet.TAG_MAX_SAMPLE_VALUE, "Hsmall");
        cFFExpertCharset.addSID(63, BaselineTIFFTagSet.TAG_X_RESOLUTION, "Ismall");
        cFFExpertCharset.addSID(64, BaselineTIFFTagSet.TAG_Y_RESOLUTION, "Jsmall");
        cFFExpertCharset.addSID(65, BaselineTIFFTagSet.TAG_PLANAR_CONFIGURATION, "Ksmall");
        cFFExpertCharset.addSID(66, BaselineTIFFTagSet.TAG_PAGE_NAME, "Lsmall");
        cFFExpertCharset.addSID(67, BaselineTIFFTagSet.TAG_X_POSITION, "Msmall");
        cFFExpertCharset.addSID(68, BaselineTIFFTagSet.TAG_Y_POSITION, "Nsmall");
        cFFExpertCharset.addSID(69, BaselineTIFFTagSet.TAG_FREE_OFFSETS, "Osmall");
        cFFExpertCharset.addSID(70, BaselineTIFFTagSet.TAG_FREE_BYTE_COUNTS, "Psmall");
        cFFExpertCharset.addSID(71, BaselineTIFFTagSet.TAG_GRAY_RESPONSE_UNIT, "Qsmall");
        cFFExpertCharset.addSID(72, BaselineTIFFTagSet.TAG_GRAY_RESPONSE_CURVE, "Rsmall");
        cFFExpertCharset.addSID(73, BaselineTIFFTagSet.TAG_T4_OPTIONS, "Ssmall");
        cFFExpertCharset.addSID(74, BaselineTIFFTagSet.TAG_T6_OPTIONS, "Tsmall");
        cFFExpertCharset.addSID(75, 294, "Usmall");
        cFFExpertCharset.addSID(76, 295, "Vsmall");
        cFFExpertCharset.addSID(77, BaselineTIFFTagSet.TAG_RESOLUTION_UNIT, "Wsmall");
        cFFExpertCharset.addSID(78, BaselineTIFFTagSet.TAG_PAGE_NUMBER, "Xsmall");
        cFFExpertCharset.addSID(79, 298, "Ysmall");
        cFFExpertCharset.addSID(80, 299, "Zsmall");
        cFFExpertCharset.addSID(81, 300, "colonmonetary");
        cFFExpertCharset.addSID(82, 301, "onefitted");
        cFFExpertCharset.addSID(83, 302, "rupiah");
        cFFExpertCharset.addSID(84, 303, "Tildesmall");
        cFFExpertCharset.addSID(85, 304, "exclamdownsmall");
        cFFExpertCharset.addSID(86, 305, "centoldstyle");
        cFFExpertCharset.addSID(87, 306, "Lslashsmall");
        cFFExpertCharset.addSID(88, 307, "Scaronsmall");
        cFFExpertCharset.addSID(89, 308, "Zcaronsmall");
        cFFExpertCharset.addSID(90, 309, "Dieresissmall");
        cFFExpertCharset.addSID(91, 310, "Brevesmall");
        cFFExpertCharset.addSID(92, 311, "Caronsmall");
        cFFExpertCharset.addSID(93, 312, "Dotaccentsmall");
        cFFExpertCharset.addSID(94, 313, "Macronsmall");
        cFFExpertCharset.addSID(95, 314, "figuredash");
        cFFExpertCharset.addSID(96, 315, "hypheninferior");
        cFFExpertCharset.addSID(97, 316, "Ogoneksmall");
        cFFExpertCharset.addSID(98, 317, "Ringsmall");
        cFFExpertCharset.addSID(99, 318, "Cedillasmall");
        cFFExpertCharset.addSID(100, 158, "onequarter");
        cFFExpertCharset.addSID(101, CipherSuite.TLS_DH_anon_WITH_SEED_CBC_SHA, "onehalf");
        cFFExpertCharset.addSID(102, CipherSuite.TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, "threequarters");
        cFFExpertCharset.addSID(103, BaselineTIFFTagSet.TAG_PRIMARY_CHROMATICITES, "questiondownsmall");
        cFFExpertCharset.addSID(104, BaselineTIFFTagSet.TAG_COLOR_MAP, "oneeighth");
        cFFExpertCharset.addSID(105, BaselineTIFFTagSet.TAG_HALFTONE_HINTS, "threeeighths");
        cFFExpertCharset.addSID(106, BaselineTIFFTagSet.TAG_TILE_WIDTH, "fiveeighths");
        cFFExpertCharset.addSID(107, BaselineTIFFTagSet.TAG_TILE_LENGTH, "seveneighths");
        cFFExpertCharset.addSID(108, BaselineTIFFTagSet.TAG_TILE_OFFSETS, "onethird");
        cFFExpertCharset.addSID(109, BaselineTIFFTagSet.TAG_TILE_BYTE_COUNTS, "twothirds");
        cFFExpertCharset.addSID(110, FaxTIFFTagSet.TAG_BAD_FAX_LINES, "zerosuperior");
        cFFExpertCharset.addSID(111, CipherSuite.TLS_RSA_WITH_SEED_CBC_SHA, "onesuperior");
        cFFExpertCharset.addSID(112, CipherSuite.TLS_DH_DSS_WITH_AES_128_GCM_SHA256, "twosuperior");
        cFFExpertCharset.addSID(113, CipherSuite.TLS_PSK_WITH_AES_256_GCM_SHA384, "threesuperior");
        cFFExpertCharset.addSID(114, FaxTIFFTagSet.TAG_CLEAN_FAX_DATA, "foursuperior");
        cFFExpertCharset.addSID(115, FaxTIFFTagSet.TAG_CONSECUTIVE_BAD_LINES, "fivesuperior");
        cFFExpertCharset.addSID(116, 329, "sixsuperior");
        cFFExpertCharset.addSID(117, 330, "sevensuperior");
        cFFExpertCharset.addSID(118, 331, "eightsuperior");
        cFFExpertCharset.addSID(119, BaselineTIFFTagSet.TAG_INK_SET, "ninesuperior");
        cFFExpertCharset.addSID(120, BaselineTIFFTagSet.TAG_INK_NAMES, "zeroinferior");
        cFFExpertCharset.addSID(121, BaselineTIFFTagSet.TAG_NUMBER_OF_INKS, "oneinferior");
        cFFExpertCharset.addSID(122, 335, "twoinferior");
        cFFExpertCharset.addSID(123, BaselineTIFFTagSet.TAG_DOT_RANGE, "threeinferior");
        cFFExpertCharset.addSID(124, BaselineTIFFTagSet.TAG_TARGET_PRINTER, "fourinferior");
        cFFExpertCharset.addSID(125, BaselineTIFFTagSet.TAG_EXTRA_SAMPLES, "fiveinferior");
        cFFExpertCharset.addSID(126, BaselineTIFFTagSet.TAG_SAMPLE_FORMAT, "sixinferior");
        cFFExpertCharset.addSID(127, BaselineTIFFTagSet.TAG_S_MIN_SAMPLE_VALUE, "seveninferior");
        cFFExpertCharset.addSID(128, 341, "eightinferior");
        cFFExpertCharset.addSID(129, BaselineTIFFTagSet.TAG_TRANSFER_RANGE, "nineinferior");
        cFFExpertCharset.addSID(130, 343, "centinferior");
        cFFExpertCharset.addSID(ISO781611.CREATION_DATE_AND_TIME_TAG, 344, "dollarinferior");
        cFFExpertCharset.addSID(CipherSuite.TLS_RSA_WITH_CAMELLIA_256_CBC_SHA, 345, "periodinferior");
        cFFExpertCharset.addSID(133, 346, "commainferior");
        cFFExpertCharset.addSID(134, BaselineTIFFTagSet.TAG_JPEG_TABLES, "Agravesmall");
        cFFExpertCharset.addSID(135, 348, "Aacutesmall");
        cFFExpertCharset.addSID(136, 349, "Acircumflexsmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA, 350, "Atildesmall");
        cFFExpertCharset.addSID(138, 351, "Adieresissmall");
        cFFExpertCharset.addSID(139, 352, "Aringsmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_PSK_WITH_AES_128_CBC_SHA, 353, "AEsmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_PSK_WITH_AES_256_CBC_SHA, 354, "Ccedillasmall");
        cFFExpertCharset.addSID(142, 355, "Egravesmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA, 356, "Eacutesmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_DHE_PSK_WITH_AES_128_CBC_SHA, 357, "Ecircumflexsmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_DHE_PSK_WITH_AES_256_CBC_SHA, 358, "Edieresissmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_RSA_PSK_WITH_RC4_128_SHA, 359, "Igravesmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA, 360, "Iacutesmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_RSA_PSK_WITH_AES_128_CBC_SHA, 361, "Icircumflexsmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_RSA_PSK_WITH_AES_256_CBC_SHA, 362, "Idieresissmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_RSA_WITH_SEED_CBC_SHA, 363, "Ethsmall");
        cFFExpertCharset.addSID(151, 364, "Ntildesmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_DH_RSA_WITH_SEED_CBC_SHA, 365, "Ogravesmall");
        cFFExpertCharset.addSID(153, 366, "Oacutesmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_DHE_RSA_WITH_SEED_CBC_SHA, 367, "Ocircumflexsmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_DH_anon_WITH_SEED_CBC_SHA, 368, "Otildesmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_RSA_WITH_AES_128_GCM_SHA256, 369, "Odieresissmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_RSA_WITH_AES_256_GCM_SHA384, 370, "OEsmall");
        cFFExpertCharset.addSID(158, 371, "Oslashsmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, 372, "Ugravesmall");
        cFFExpertCharset.addSID(160, 373, "Uacutesmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_DH_RSA_WITH_AES_256_GCM_SHA384, 374, "Ucircumflexsmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, 375, "Udieresissmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, 376, "Yacutesmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_DH_DSS_WITH_AES_128_GCM_SHA256, 377, "Thornsmall");
        cFFExpertCharset.addSID(CipherSuite.TLS_DH_DSS_WITH_AES_256_GCM_SHA384, 378, "Ydieresissmall");
    }
}
