package org.apache.fontbox.cff;

import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.media3.exoplayer.upstream.CmcdData;
import androidx.media3.extractor.text.ttml.TtmlNode;
import com.google.firebase.analytics.FirebaseAnalytics;
import com.google.firebase.dynamiclinks.DynamicLink;
import com.google.mlkit.common.MlKitException;
import io.sentry.profilemeasurements.ProfileMeasurement;
import io.sentry.protocol.ViewHierarchyNode;
import org.apache.pdfbox.pdmodel.common.PDPageLabelRange;
import org.apache.pdfbox.pdmodel.documentinterchange.taggedpdf.StandardStructureTypes;
import org.apache.pdfbox.pdmodel.interactive.annotation.PDAnnotationLink;
import org.apache.pdfbox.pdmodel.interactive.annotation.PDBorderStyleDictionary;
import org.apache.pdfbox.pdmodel.interactive.measurement.PDNumberFormatDictionary;
import org.bouncycastle.crypto.tls.CipherSuite;
import org.bouncycastle.math.Primes;
import org.jmrtd.cbeff.ISO781611;

/* loaded from: classes5.dex */
public final class CFFISOAdobeCharset extends CFFCharset {
    private static final CFFISOAdobeCharset INSTANCE;

    private CFFISOAdobeCharset() {
        super(false);
    }

    public static CFFISOAdobeCharset getInstance() {
        return INSTANCE;
    }

    static {
        CFFISOAdobeCharset cFFISOAdobeCharset = new CFFISOAdobeCharset();
        INSTANCE = cFFISOAdobeCharset;
        cFFISOAdobeCharset.addSID(0, 0, ".notdef");
        cFFISOAdobeCharset.addSID(1, 1, "space");
        cFFISOAdobeCharset.addSID(2, 2, "exclam");
        cFFISOAdobeCharset.addSID(3, 3, "quotedbl");
        cFFISOAdobeCharset.addSID(4, 4, "numbersign");
        cFFISOAdobeCharset.addSID(5, 5, "dollar");
        cFFISOAdobeCharset.addSID(6, 6, ProfileMeasurement.UNIT_PERCENT);
        cFFISOAdobeCharset.addSID(7, 7, "ampersand");
        cFFISOAdobeCharset.addSID(8, 8, "quoteright");
        cFFISOAdobeCharset.addSID(9, 9, "parenleft");
        cFFISOAdobeCharset.addSID(10, 10, "parenright");
        cFFISOAdobeCharset.addSID(11, 11, "asterisk");
        cFFISOAdobeCharset.addSID(12, 12, "plus");
        cFFISOAdobeCharset.addSID(13, 13, "comma");
        cFFISOAdobeCharset.addSID(14, 14, "hyphen");
        cFFISOAdobeCharset.addSID(15, 15, TypedValues.CycleType.S_WAVE_PERIOD);
        cFFISOAdobeCharset.addSID(16, 16, "slash");
        cFFISOAdobeCharset.addSID(17, 17, "zero");
        cFFISOAdobeCharset.addSID(18, 18, "one");
        cFFISOAdobeCharset.addSID(19, 19, "two");
        cFFISOAdobeCharset.addSID(20, 20, "three");
        cFFISOAdobeCharset.addSID(21, 21, "four");
        cFFISOAdobeCharset.addSID(22, 22, "five");
        cFFISOAdobeCharset.addSID(23, 23, "six");
        cFFISOAdobeCharset.addSID(24, 24, "seven");
        cFFISOAdobeCharset.addSID(25, 25, "eight");
        cFFISOAdobeCharset.addSID(26, 26, "nine");
        cFFISOAdobeCharset.addSID(27, 27, "colon");
        cFFISOAdobeCharset.addSID(28, 28, "semicolon");
        cFFISOAdobeCharset.addSID(29, 29, "less");
        cFFISOAdobeCharset.addSID(30, 30, "equal");
        cFFISOAdobeCharset.addSID(31, 31, "greater");
        cFFISOAdobeCharset.addSID(32, 32, "question");
        cFFISOAdobeCharset.addSID(33, 33, DynamicLink.ItunesConnectAnalyticsParameters.KEY_ITUNES_CONNECT_AT);
        cFFISOAdobeCharset.addSID(34, 34, "A");
        cFFISOAdobeCharset.addSID(35, 35, "B");
        cFFISOAdobeCharset.addSID(36, 36, "C");
        cFFISOAdobeCharset.addSID(37, 37, "D");
        cFFISOAdobeCharset.addSID(38, 38, "E");
        cFFISOAdobeCharset.addSID(39, 39, PDNumberFormatDictionary.FRACTIONAL_DISPLAY_FRACTION);
        cFFISOAdobeCharset.addSID(40, 40, "G");
        cFFISOAdobeCharset.addSID(41, 41, StandardStructureTypes.H);
        cFFISOAdobeCharset.addSID(42, 42, "I");
        cFFISOAdobeCharset.addSID(43, 43, "J");
        cFFISOAdobeCharset.addSID(44, 44, "K");
        cFFISOAdobeCharset.addSID(45, 45, "L");
        cFFISOAdobeCharset.addSID(46, 46, "M");
        cFFISOAdobeCharset.addSID(47, 47, "N");
        cFFISOAdobeCharset.addSID(48, 48, PDAnnotationLink.HIGHLIGHT_MODE_OUTLINE);
        cFFISOAdobeCharset.addSID(49, 49, "P");
        cFFISOAdobeCharset.addSID(50, 50, "Q");
        cFFISOAdobeCharset.addSID(51, 51, "R");
        cFFISOAdobeCharset.addSID(52, 52, "S");
        cFFISOAdobeCharset.addSID(53, 53, "T");
        cFFISOAdobeCharset.addSID(54, 54, PDBorderStyleDictionary.STYLE_UNDERLINE);
        cFFISOAdobeCharset.addSID(55, 55, "V");
        cFFISOAdobeCharset.addSID(56, 56, "W");
        cFFISOAdobeCharset.addSID(57, 57, "X");
        cFFISOAdobeCharset.addSID(58, 58, "Y");
        cFFISOAdobeCharset.addSID(59, 59, "Z");
        cFFISOAdobeCharset.addSID(60, 60, "bracketleft");
        cFFISOAdobeCharset.addSID(61, 61, "backslash");
        cFFISOAdobeCharset.addSID(62, 62, "bracketright");
        cFFISOAdobeCharset.addSID(63, 63, "asciicircum");
        cFFISOAdobeCharset.addSID(64, 64, "underscore");
        cFFISOAdobeCharset.addSID(65, 65, "quoteleft");
        cFFISOAdobeCharset.addSID(66, 66, "a");
        cFFISOAdobeCharset.addSID(67, 67, "b");
        cFFISOAdobeCharset.addSID(68, 68, "c");
        cFFISOAdobeCharset.addSID(69, 69, "d");
        cFFISOAdobeCharset.addSID(70, 70, "e");
        cFFISOAdobeCharset.addSID(71, 71, "f");
        cFFISOAdobeCharset.addSID(72, 72, "g");
        cFFISOAdobeCharset.addSID(73, 73, CmcdData.Factory.STREAMING_FORMAT_HLS);
        cFFISOAdobeCharset.addSID(74, 74, CmcdData.Factory.OBJECT_TYPE_INIT_SEGMENT);
        cFFISOAdobeCharset.addSID(75, 75, "j");
        cFFISOAdobeCharset.addSID(76, 76, "k");
        cFFISOAdobeCharset.addSID(77, 77, CmcdData.Factory.STREAM_TYPE_LIVE);
        cFFISOAdobeCharset.addSID(78, 78, "m");
        cFFISOAdobeCharset.addSID(79, 79, "n");
        cFFISOAdobeCharset.addSID(80, 80, "o");
        cFFISOAdobeCharset.addSID(81, 81, TtmlNode.TAG_P);
        cFFISOAdobeCharset.addSID(82, 82, "q");
        cFFISOAdobeCharset.addSID(83, 83, PDPageLabelRange.STYLE_ROMAN_LOWER);
        cFFISOAdobeCharset.addSID(84, 84, CmcdData.Factory.STREAMING_FORMAT_SS);
        cFFISOAdobeCharset.addSID(85, 85, "t");
        cFFISOAdobeCharset.addSID(86, 86, "u");
        cFFISOAdobeCharset.addSID(87, 87, "v");
        cFFISOAdobeCharset.addSID(88, 88, "w");
        cFFISOAdobeCharset.addSID(89, 89, ViewHierarchyNode.JsonKeys.X);
        cFFISOAdobeCharset.addSID(90, 90, ViewHierarchyNode.JsonKeys.Y);
        cFFISOAdobeCharset.addSID(91, 91, "z");
        cFFISOAdobeCharset.addSID(92, 92, "braceleft");
        cFFISOAdobeCharset.addSID(93, 93, "bar");
        cFFISOAdobeCharset.addSID(94, 94, "braceright");
        cFFISOAdobeCharset.addSID(95, 95, "asciitilde");
        cFFISOAdobeCharset.addSID(96, 96, "exclamdown");
        cFFISOAdobeCharset.addSID(97, 97, "cent");
        cFFISOAdobeCharset.addSID(98, 98, "sterling");
        cFFISOAdobeCharset.addSID(99, 99, "fraction");
        cFFISOAdobeCharset.addSID(100, 100, "yen");
        cFFISOAdobeCharset.addSID(101, 101, "florin");
        cFFISOAdobeCharset.addSID(102, 102, "section");
        cFFISOAdobeCharset.addSID(103, 103, FirebaseAnalytics.Param.CURRENCY);
        cFFISOAdobeCharset.addSID(104, 104, "quotesingle");
        cFFISOAdobeCharset.addSID(105, 105, "quotedblleft");
        cFFISOAdobeCharset.addSID(106, 106, "guillemotleft");
        cFFISOAdobeCharset.addSID(107, 107, "guilsinglleft");
        cFFISOAdobeCharset.addSID(108, 108, "guilsinglright");
        cFFISOAdobeCharset.addSID(109, 109, "fi");
        cFFISOAdobeCharset.addSID(110, 110, "fl");
        cFFISOAdobeCharset.addSID(111, 111, "endash");
        cFFISOAdobeCharset.addSID(112, 112, "dagger");
        cFFISOAdobeCharset.addSID(113, 113, "daggerdbl");
        cFFISOAdobeCharset.addSID(114, 114, "periodcentered");
        cFFISOAdobeCharset.addSID(115, 115, "paragraph");
        cFFISOAdobeCharset.addSID(116, 116, "bullet");
        cFFISOAdobeCharset.addSID(117, 117, "quotesinglbase");
        cFFISOAdobeCharset.addSID(118, 118, "quotedblbase");
        cFFISOAdobeCharset.addSID(119, 119, "quotedblright");
        cFFISOAdobeCharset.addSID(120, 120, "guillemotright");
        cFFISOAdobeCharset.addSID(121, 121, "ellipsis");
        cFFISOAdobeCharset.addSID(122, 122, "perthousand");
        cFFISOAdobeCharset.addSID(123, 123, "questiondown");
        cFFISOAdobeCharset.addSID(124, 124, "grave");
        cFFISOAdobeCharset.addSID(125, 125, "acute");
        cFFISOAdobeCharset.addSID(126, 126, "circumflex");
        cFFISOAdobeCharset.addSID(127, 127, "tilde");
        cFFISOAdobeCharset.addSID(128, 128, "macron");
        cFFISOAdobeCharset.addSID(129, 129, "breve");
        cFFISOAdobeCharset.addSID(130, 130, "dotaccent");
        cFFISOAdobeCharset.addSID(ISO781611.CREATION_DATE_AND_TIME_TAG, ISO781611.CREATION_DATE_AND_TIME_TAG, "dieresis");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_RSA_WITH_CAMELLIA_256_CBC_SHA, CipherSuite.TLS_RSA_WITH_CAMELLIA_256_CBC_SHA, "ring");
        cFFISOAdobeCharset.addSID(133, 133, "cedilla");
        cFFISOAdobeCharset.addSID(134, 134, "hungarumlaut");
        cFFISOAdobeCharset.addSID(135, 135, "ogonek");
        cFFISOAdobeCharset.addSID(136, 136, "caron");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA, CipherSuite.TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA, "emdash");
        cFFISOAdobeCharset.addSID(138, 138, "AE");
        cFFISOAdobeCharset.addSID(139, 139, "ordfeminine");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_PSK_WITH_AES_128_CBC_SHA, CipherSuite.TLS_PSK_WITH_AES_128_CBC_SHA, "Lslash");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_PSK_WITH_AES_256_CBC_SHA, CipherSuite.TLS_PSK_WITH_AES_256_CBC_SHA, "Oslash");
        cFFISOAdobeCharset.addSID(142, 142, "OE");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA, CipherSuite.TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA, "ordmasculine");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DHE_PSK_WITH_AES_128_CBC_SHA, CipherSuite.TLS_DHE_PSK_WITH_AES_128_CBC_SHA, "ae");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DHE_PSK_WITH_AES_256_CBC_SHA, CipherSuite.TLS_DHE_PSK_WITH_AES_256_CBC_SHA, "dotlessi");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_RSA_PSK_WITH_RC4_128_SHA, CipherSuite.TLS_RSA_PSK_WITH_RC4_128_SHA, "lslash");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA, CipherSuite.TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA, "oslash");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_RSA_PSK_WITH_AES_128_CBC_SHA, CipherSuite.TLS_RSA_PSK_WITH_AES_128_CBC_SHA, "oe");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_RSA_PSK_WITH_AES_256_CBC_SHA, CipherSuite.TLS_RSA_PSK_WITH_AES_256_CBC_SHA, "germandbls");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_RSA_WITH_SEED_CBC_SHA, CipherSuite.TLS_RSA_WITH_SEED_CBC_SHA, "onesuperior");
        cFFISOAdobeCharset.addSID(151, 151, "logicalnot");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DH_RSA_WITH_SEED_CBC_SHA, CipherSuite.TLS_DH_RSA_WITH_SEED_CBC_SHA, "mu");
        cFFISOAdobeCharset.addSID(153, 153, "trademark");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DHE_RSA_WITH_SEED_CBC_SHA, CipherSuite.TLS_DHE_RSA_WITH_SEED_CBC_SHA, "Eth");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DH_anon_WITH_SEED_CBC_SHA, CipherSuite.TLS_DH_anon_WITH_SEED_CBC_SHA, "onehalf");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_RSA_WITH_AES_128_GCM_SHA256, CipherSuite.TLS_RSA_WITH_AES_128_GCM_SHA256, "plusminus");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_RSA_WITH_AES_256_GCM_SHA384, CipherSuite.TLS_RSA_WITH_AES_256_GCM_SHA384, "Thorn");
        cFFISOAdobeCharset.addSID(158, 158, "onequarter");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, CipherSuite.TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, "divide");
        cFFISOAdobeCharset.addSID(160, 160, "brokenbar");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DH_RSA_WITH_AES_256_GCM_SHA384, CipherSuite.TLS_DH_RSA_WITH_AES_256_GCM_SHA384, "degree");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, CipherSuite.TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, "thorn");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, CipherSuite.TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, "threequarters");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DH_DSS_WITH_AES_128_GCM_SHA256, CipherSuite.TLS_DH_DSS_WITH_AES_128_GCM_SHA256, "twosuperior");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DH_DSS_WITH_AES_256_GCM_SHA384, CipherSuite.TLS_DH_DSS_WITH_AES_256_GCM_SHA384, "registered");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DH_anon_WITH_AES_128_GCM_SHA256, CipherSuite.TLS_DH_anon_WITH_AES_128_GCM_SHA256, "minus");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DH_anon_WITH_AES_256_GCM_SHA384, CipherSuite.TLS_DH_anon_WITH_AES_256_GCM_SHA384, "eth");
        cFFISOAdobeCharset.addSID(168, 168, "multiply");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_PSK_WITH_AES_256_GCM_SHA384, CipherSuite.TLS_PSK_WITH_AES_256_GCM_SHA384, "threesuperior");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DHE_PSK_WITH_AES_128_GCM_SHA256, CipherSuite.TLS_DHE_PSK_WITH_AES_128_GCM_SHA256, "copyright");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DHE_PSK_WITH_AES_256_GCM_SHA384, CipherSuite.TLS_DHE_PSK_WITH_AES_256_GCM_SHA384, "Aacute");
        cFFISOAdobeCharset.addSID(172, 172, "Acircumflex");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_RSA_PSK_WITH_AES_256_GCM_SHA384, CipherSuite.TLS_RSA_PSK_WITH_AES_256_GCM_SHA384, "Adieresis");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_PSK_WITH_AES_128_CBC_SHA256, CipherSuite.TLS_PSK_WITH_AES_128_CBC_SHA256, "Agrave");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_PSK_WITH_AES_256_CBC_SHA384, CipherSuite.TLS_PSK_WITH_AES_256_CBC_SHA384, "Aring");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_PSK_WITH_NULL_SHA256, CipherSuite.TLS_PSK_WITH_NULL_SHA256, "Atilde");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_PSK_WITH_NULL_SHA384, CipherSuite.TLS_PSK_WITH_NULL_SHA384, "Ccedilla");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DHE_PSK_WITH_AES_128_CBC_SHA256, CipherSuite.TLS_DHE_PSK_WITH_AES_128_CBC_SHA256, "Eacute");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DHE_PSK_WITH_AES_256_CBC_SHA384, CipherSuite.TLS_DHE_PSK_WITH_AES_256_CBC_SHA384, "Ecircumflex");
        cFFISOAdobeCharset.addSID(180, 180, "Edieresis");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DHE_PSK_WITH_NULL_SHA384, CipherSuite.TLS_DHE_PSK_WITH_NULL_SHA384, "Egrave");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_RSA_PSK_WITH_AES_128_CBC_SHA256, CipherSuite.TLS_RSA_PSK_WITH_AES_128_CBC_SHA256, "Iacute");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_RSA_PSK_WITH_AES_256_CBC_SHA384, CipherSuite.TLS_RSA_PSK_WITH_AES_256_CBC_SHA384, "Icircumflex");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_RSA_PSK_WITH_NULL_SHA256, CipherSuite.TLS_RSA_PSK_WITH_NULL_SHA256, "Idieresis");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_RSA_PSK_WITH_NULL_SHA384, CipherSuite.TLS_RSA_PSK_WITH_NULL_SHA384, "Igrave");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256, CipherSuite.TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256, "Ntilde");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA256, CipherSuite.TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA256, "Oacute");
        cFFISOAdobeCharset.addSID(188, 188, "Ocircumflex");
        cFFISOAdobeCharset.addSID(189, 189, "Odieresis");
        cFFISOAdobeCharset.addSID(190, 190, "Ograve");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256, CipherSuite.TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256, "Otilde");
        cFFISOAdobeCharset.addSID(192, 192, "Scaron");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA256, CipherSuite.TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA256, "Uacute");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA256, CipherSuite.TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA256, "Ucircumflex");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256, CipherSuite.TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256, "Udieresis");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256, CipherSuite.TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256, "Ugrave");
        cFFISOAdobeCharset.addSID(CipherSuite.TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256, CipherSuite.TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256, "Yacute");
        cFFISOAdobeCharset.addSID(198, 198, "Ydieresis");
        cFFISOAdobeCharset.addSID(199, 199, "Zcaron");
        cFFISOAdobeCharset.addSID(200, 200, "aacute");
        cFFISOAdobeCharset.addSID(201, 201, "acircumflex");
        cFFISOAdobeCharset.addSID(202, 202, "adieresis");
        cFFISOAdobeCharset.addSID(203, 203, "agrave");
        cFFISOAdobeCharset.addSID(MlKitException.CODE_SCANNER_TASK_IN_PROGRESS, MlKitException.CODE_SCANNER_TASK_IN_PROGRESS, "aring");
        cFFISOAdobeCharset.addSID(MlKitException.CODE_SCANNER_PIPELINE_INITIALIZATION_ERROR, MlKitException.CODE_SCANNER_PIPELINE_INITIALIZATION_ERROR, "atilde");
        cFFISOAdobeCharset.addSID(MlKitException.CODE_SCANNER_PIPELINE_INFERENCE_ERROR, MlKitException.CODE_SCANNER_PIPELINE_INFERENCE_ERROR, "ccedilla");
        cFFISOAdobeCharset.addSID(MlKitException.CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD, MlKitException.CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD, "eacute");
        cFFISOAdobeCharset.addSID(208, 208, "ecircumflex");
        cFFISOAdobeCharset.addSID(209, 209, "edieresis");
        cFFISOAdobeCharset.addSID(210, 210, "egrave");
        cFFISOAdobeCharset.addSID(Primes.SMALL_FACTOR_LIMIT, Primes.SMALL_FACTOR_LIMIT, "iacute");
        cFFISOAdobeCharset.addSID(212, 212, "icircumflex");
        cFFISOAdobeCharset.addSID(213, 213, "idieresis");
        cFFISOAdobeCharset.addSID(214, 214, "igrave");
        cFFISOAdobeCharset.addSID(215, 215, "ntilde");
        cFFISOAdobeCharset.addSID(216, 216, "oacute");
        cFFISOAdobeCharset.addSID(217, 217, "ocircumflex");
        cFFISOAdobeCharset.addSID(218, 218, "odieresis");
        cFFISOAdobeCharset.addSID(219, 219, "ograve");
        cFFISOAdobeCharset.addSID(220, 220, "otilde");
        cFFISOAdobeCharset.addSID(221, 221, "scaron");
        cFFISOAdobeCharset.addSID(222, 222, "uacute");
        cFFISOAdobeCharset.addSID(223, 223, "ucircumflex");
        cFFISOAdobeCharset.addSID(224, 224, "udieresis");
        cFFISOAdobeCharset.addSID(225, 225, "ugrave");
        cFFISOAdobeCharset.addSID(226, 226, "yacute");
        cFFISOAdobeCharset.addSID(227, 227, "ydieresis");
        cFFISOAdobeCharset.addSID(228, 228, "zcaron");
    }
}
